name: PR Validation

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - run: npm install
    - run: npm run lint
  license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - run: npm install
    - run: npm run check-licenses
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2 # needed for commit-check action in case of multiple commits in the PR
    - name: Check commit
      run: make check-commit
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
