name: PR Validation

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - run: npm ci
    - run: npm run test
    - run: git diff --exit-code README.md

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - run: npm ci
    - run: npm run lint

  license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - run: npm ci
    - run: npm run check-licenses

  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci

      - name: Regenerate JSON file from YAML source
        run: npx ts-node src/scripts/yaml2json.ts

      - name: Compare snippet file
        run: git diff --exit-code snippets/styra-common.json
